import Head from "next/head";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SciREN Info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>SciREN-Net</h1>
        <div className={styles.miniNav}>
          <Link href="/" className={styles.miniLink + " " + styles.sunderline}>
            Home
          </Link>
          <a href="/sprint1" className={styles.miniLink}>
            Sprints
          </a>
          <a href="/tech" className={styles.miniLink}>
            Technical Details
          </a>
          <a href="/team" className={styles.miniLink}>
            The Team
          </a>
          <a
            href="https://github.com/pdthompson5/SciREN-Net"
            className={styles.miniLink}
          >
            Github Repo
          </a>
        </div>

        <hr></hr>
        <h2 className={styles.sheader}>Overview</h2>
        <p>
          SciREN-Net is a platform created for the Scientific Research and
          Education Network (SciREN), a graduate-student-led group from
          dedicated to connecting educators and researchers. Inspired by
          LinkedIn, this platform will allow users to share their academic
          content and find other academics ergonomically. This project is still
          in the making, and we&apos;re excited to share our progress with you!
        </p>
        <h2 className={styles.sheader}>What Problems We&apos;re Solving</h2>
        <p>
          As it stands, researchers and educators are often siloed from one
          another and are consequently unable to share cirriculum efficiently.
          Often times, educators are not aware of the teaching resources that
          exist in their own region, and researchers have trouble getting their
          lessons into the hands of such professionals. Our platform will solve
          both problems by creating a modern medium for researchers to share
          their lesson plans with educators across any academic institution
          while simultaniously funcitoning as a social platform where users can
          connect and communicate.
        </p>
        <h2 className={styles.sheader}>Feature Overview</h2>
        <h3 className={styles.sheader1}>Networking</h3>
        <ul>
          <li className={styles.sli}>
            <b>Sign-in/up: </b>Like any social platform, users should be able to
            register an account and sign-in with their saved credentials.
          </li>
          <li className={styles.sli}>
            <b>Profile: </b>Since we&apos;re targeting educational
            professionals, it&apos;s important to collect information like
            academic field, organization, target grades, and title.
          </li>
          <li className={styles.sli}>
            <b>Contact: </b>To protect users from spam, an in-app contact
            solution will allow users to connect without directly exposing their
            emails.
          </li>
          <li className={styles.sli}>
            <b>Search: </b>Helping users find eachother is top-priority, so a
            system to easily search users by field and organization will be
            implemented.
          </li>
        </ul>
        <h3 className={styles.sheader1}>Cirriculum Sharing</h3>
        <ul>
          <li className={styles.sli}>
            <b>Storage: </b>SciREN will act as a repository for lesson plans,
            where users can search for their desired content.
          </li>
          <li className={styles.sli}>
            <b>Create: </b>Users will be able to create and upload their own
            lesson plans through this platform, including documents and all the
            necessary media.
          </li>
          <li className={styles.sli}>
            <b>Interact: </b>Cirriculum can be modified or deleted by the owning
            user, and we hope to implement a rating system for improved
            expsoure.
          </li>
        </ul>
        <h3 className={styles.sheader1}>Academic Calendar</h3>
        <ul>
          <li className={styles.sli}>
            <b>View: </b>SciREN will host an academic calendar for all users to
            see, displaying networking events, seminars, and other events.
          </li>
          <li className={styles.sli}>
            <b>Create: </b>Users will be able to create and upload their own
            events once authenticated, helping them reach others in their
            region.
          </li>
        </ul>
      </main>
    </>
  );
}
